title: "Med Info"
baseurl: "/med-info"
url: "https://medicalchange.github.io"
timezone: America/New_York
markdown: kramdown
permalink: pretty
theme: minima
plugins:
  - jekyll-feed

# Privacy-friendly analytics (optional): set goatcounter_site to enable.
analytics_provider: goatcounter
goatcounter_site: "ydafus"
