title: "Med Info"
baseurl: ""
url: "https://medicallinks.ca"
timezone: America/New_York
markdown: kramdown
permalink: pretty
theme: minima
plugins:
  - jekyll-feed

# Privacy-friendly analytics (optional): set goatcounter_site to enable.
analytics_provider: goatcounter
goatcounter_site: "ydafus"
